config/routes.rb
Rails.application.routes.draw do


  resources :user_stocks, only: [:create,:update, :destroy]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends' , to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/views/friends/_list.html.erb
<div class="row">
    <div class="col-9">
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th scope="col">Email</th>
                <th scope="col">Friend Name</th>
                <th scope="col">Actions</th>

            </tr>
            </thead>
            
            <tbody>
            <% @friends.each do |friend| %>
                <tr>
                <td><%= friend.email %></td>
                <td><%= friend.first_name %> <%= friend.last_name %></td>
                <td><%= link_to 'Stop following', friendship_path(friend) , 
                                                  method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-warning' %>
                    <%= link_to 'View Profile', user_path(friend) , class: 'btn btn-sm btn-success' %></td>
                
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>
</div>