config/routes.rb
Rails.application.routes.draw do


  resources :user_stocks, only: [:create,:update, :destroy]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends' , to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock 
    stocks.where(id: stock.id).exists?
  end
  
  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param) 
  end

  def self.matches(field_name, param)   #self so that convert it to class method not write User
    where("#{field_name} like ?", "%#{param}%")
  end
  def except_current_user(users)
    users.reject {|user| user.id == self.id}
  end

  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def my_portfolio
      #@users = User.all
      @user = current_user
      @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def show 
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def search 
    #byebug
    #render json: params[:friend]
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      #byebug
      if @friends
          respond_to do |format|
            format.js {render partial: 'users/friend_result'}
          end
      else
          respond_to do |format|
            flash.now[:alert] = "Couldn`t find user"
            format.js {render partial: 'users/friend_result'}
          end
      end
    else
          respond_to do |format|
              flash.now[:alert] = "Please enter a friend name ot email to search"
              format.js {render partial: 'users/friend_result'}
          end
    end
  end

 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend_result.html.erb
<div class="results-block">
    <%= render 'layouts/messages' %>
</div>

<% if @friends %>
    <div class="card card-header results-block">
        <table class="col-md12">
            <tbody>
                <% @friends.each do |friend| %> 
                    <tr>
                        <td><strong>Name:</strong> <%= friend.full_name %></td>
                        <td><strong>Email:</strong> <%= friend.email %></td>
                        <td><strong>Action:</strong> <%= link_to "View Profile", user_path(friend), class: 'btn btn-sm btn-success' %>
                        <% if current_user.not_friends_with?(friend.id) %>
                            <%= link_to 'follow friend', friendships_path(friend: friend), method: :post, class: "btn btn-sm btn-success" %>
                        <% else %>
                            <span class="badge badge-secondary">
                            You are friends
                            </span>
                        <% end %>
                        </td>
                    </tr>
                <% end %>
            <tbody>
        <table>
    </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#friend_results').innerHTML = '<%= j render 'users/friend_result.html' %>'

app/views/users/_result.html.erb
<div class="results-block">
    <%= render 'layouts/messages' %>
</div>

<% if @stock %>
    <div class="card card-header results-block">
        <strong>Symbol:</strong> <%= @stock.ticker %>
        <strong>Name:</strong> <%= @stock.name %>
        <strong>Price:</strong> <%= @stock.last_price %>

        <% if current_user.can_track_stock?(@stock.ticker) %>
            <%= link_to "Add to portfolio", user_stocks_path(user: current_user, ticker: @stock.ticker),
                                            class: "btn btn-xs btn-success", method: :post %>
        <% else %>
            <span class="badge badge-secondary">
            You are already tracking
            <% if !current_user.under_stock_limit? %>
                10 stocks
            <% end %>
            <% if current_user.stock_already_tracked?(@stock.ticker) %>
                this stock 
            <% end %>
            </span>
        <% end %>
    </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/result.html' %>'

app/views/users/my_friends.html.erb
<h1>Friends</h1>

<div class='search-area'>
    <h3>Search Friends</h3>
    <%= form_tag search_friend_path, remote: true, method: :get do %>
        <div class="form-group row">
            <div class="col-sm-9  no-right-padding">
                <%= text_field_tag :friend, params[:friend], placholder: "Enter Name", autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class="col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

<div id="friend_results"></div>

<% if !@friends.empty? %>
    <%= render 'friends/list' %>
<% else %>
    <h2>You are not following any friends yet</h2>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>


<div class="row justify-content-end">
  <div class="col-4">
      <%= link_to 'Update Prices' , user_stock_path(current_user.id), class: "btn btn-lg btn-success", :method => "put" %>
  </div>
</div>
    

<div class='search-area'>
    <h3>Search Stock</h3>
    <%= form_tag search_stock_path, remote: true, method: :get do %>
        <div class="form-group row">
            <div class="col-sm-9  no-right-padding">
                <%= text_field_tag :stock, params[:stock], placholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class="col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

<div id="results"></div>

<% if !@tracked_stocks.empty? %>
    <%= render 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h4>User Details</h4>

<% if !@tracked_stocks.empty? %>
    <%= render 'stocks/list' %>
<% else %>
    <p class='lead'> This user is not tracking any stocks</p>
<% end %>

<div class="card card-header results-block">
    <table class="col-md12">
        <tbody>
                <tr>
                    <td><strong>Name:</strong> <%= @user.full_name %></td>
                    <td><strong>Email:</strong> <%= @user.email %></td>
                    <td><strong>Action:</strong> <%= link_to "View Profile", user_path, class: 'btn btn-sm btn-success' %>
                    <% if current_user.not_friends_with?(@user.id) %>
                        <%= link_to 'follow friend', friendships_path(friend: @user), method: :post, class: "btn btn-sm btn-success" %>
                    <% else %>
                        <span class="badge badge-secondary">
                        You are friends
                        </span>
                    <% end %>
                    </td>
                </tr>
        <tbody>
    <table>

</div>